import { useEffect, useRef } from "react";
import * as THREE from "three";
import {
  createAaronFacetedBustModel,
  createAaronFacetedBustLookDevLights,
  createAaronFacetedBustEnvironment,
  frameAaronFacetedBustCamera,
  configureAaronFacetedBustRenderer,
  createAaronFacetedBustInspectControls,
} from "~/three/createAaronBust";
import { usePrefersReducedMotion } from "~/hooks/usePrefersReducedMotion";

/**
 * The hero portrait's third dimension: the same acetate-plane palette given
 * real depth, generated by the img2threejs pipeline from Aaron's own photo
 * (see .img2threejs/ and app/three/createAaronBust.ts for the full
 * reconstruction trail). Drag to orbit; a small idle sway keeps it feeling
 * alive when no one's touching it, the same "always a little bit moving"
 * language as the rest of the site's react-spring animation — just driven
 * by Three.js's own render loop instead of a spring, since this is a
 * continuous 3D rotation, not a discrete from/to transition.
 */
export function AaronBust3D() {
  const containerRef = useRef<HTMLDivElement>(null);
  const reduced = usePrefersReducedMotion();

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(40, 1, 0.1, 30);

    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    configureAaronFacetedBustRenderer(renderer);
    renderer.shadowMap.enabled = true;
    renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    container.appendChild(renderer.domElement);

    const model = createAaronFacetedBustModel();
    // The generic template's root pivot renders as its own unit sphere,
    // sized for a full-body rig's hip-height root -- in this bust's
    // coordinate frame that sphere sits inside the torso/neck and would
    // show through as a stray dark shape. It carries no visible geometry
    // of its own (material "hidden"), so hiding it is correct, not a
    // patch over a real part.
    const rootPivot = model.getObjectByName("Bust (root)");
    if (rootPivot) rootPivot.visible = false;
    scene.add(model);

    const lights = createAaronFacetedBustLookDevLights("neutral");
    scene.add(lights);
    scene.environment = createAaronFacetedBustEnvironment(renderer);

    frameAaronFacetedBustCamera(camera, model, { margin: 1.35, elevationDeg: 4 });

    const controls = createAaronFacetedBustInspectControls(camera, renderer.domElement);
    controls.target.set(0, 0.45, 0);
    controls.enablePan = false;
    controls.autoRotate = false;
    controls.update();

    function resize() {
      if (!container) return;
      const { clientWidth, clientHeight } = container;
      if (clientWidth === 0 || clientHeight === 0) return;
      camera.aspect = clientWidth / clientHeight;
      camera.updateProjectionMatrix();
      renderer.setSize(clientWidth, clientHeight);
      renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    }
    resize();
    const resizeObserver = new ResizeObserver(resize);
    resizeObserver.observe(container);

    let raf = 0;
    let disposed = false;
    const clock = new THREE.Clock();

    function tick() {
      if (disposed) return;
      // Idle sway: a slow, small yaw so the bust never sits perfectly
      // still when the visitor isn't dragging it -- amplitude is tiny on
      // purpose, this is a "still alive" cue, not a spin.
      if (!reduced) {
        model.rotation.y = Math.sin(clock.getElapsedTime() * 0.4) * 0.12;
      }
      controls.update();
      renderer.render(scene, camera);
      raf = requestAnimationFrame(tick);
    }
    tick();

    return () => {
      disposed = true;
      cancelAnimationFrame(raf);
      resizeObserver.disconnect();
      controls.dispose();
      renderer.dispose();
      scene.environment?.dispose();
      model.traverse((obj) => {
        if (obj instanceof THREE.Mesh) {
          obj.geometry.dispose();
          const mats = Array.isArray(obj.material) ? obj.material : [obj.material];
          mats.forEach((m) => m.dispose());
        }
      });
      container.removeChild(renderer.domElement);
    };
  }, [reduced]);

  return (
    <div
      ref={containerRef}
      className="aspect-square w-full cursor-grab touch-none active:cursor-grabbing"
      role="img"
      aria-label="An interactive 3D portrait of Aaron Parisi, built from the same acetate-plane palette as the hero image. Drag to rotate."
    />
  );
}
